services:
  discord-cacher:
    build: .
    container_name: discord-cacher
    restart: unless-stopped
    network_mode: host
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /mnt:/mnt
